import express, { Request, Response } from 'express';
import { runRagWorkflow, stateStore } from '../graph/workflow';

const router = express.Router();

/**
 * GET /api/rag/state/:documentId
 * Retrieves the current LangGraph state snapshot for educational observability.
 */
router.get('/state/:documentId', (req: Request, res: Response): void => {
  const documentId = String(req.params.documentId || '');
  const state = stateStore.get(documentId);

  if (!state) {
    res.status(404).json({ error: `No state found for document ID '${documentId}'.` });
    return;
  }

  res.json({ success: true, state });
});

/**
 * POST /api/rag/resume
 * Resumes LangGraph execution from an educational HITL breakpoint.
 * Allows students to tweak topK or similarity threshold before generating the final answer.
 */
router.post('/resume', async (req: Request, res: Response): Promise<void> => {
  try {
    const { documentId, updatedParams, action } = req.body;

    if (!documentId) {
      res.status(400).json({ error: 'documentId is required.' });
      return;
    }

    const existingState = stateStore.get(documentId);
    if (!existingState) {
      res.status(404).json({ error: 'Document state not found in session memory.' });
      return;
    }

    console.log(`▶️ [API /resume] Resuming graph for '${documentId}'. Current status: '${existingState.stepStatus}'`);

    // If resuming from Ingestion inspection, transition to IDLE waiting for user queries
    if (existingState.stepStatus === 'WAITING_FOR_INSPECTION_INGESTION') {
      const state = await runRagWorkflow({
        documentId,
        stepStatus: 'IDLE',
      });
      res.json({
        success: true,
        message: 'Ingestion inspection acknowledged. Ready for student queries.',
        state,
      });
      return;
    }

    // If resuming from Retrieval inspection, if params changed, re-run retrieval first or proceed to GENERATING
    if (existingState.stepStatus === 'WAITING_FOR_INSPECTION_RETRIEVAL') {
      const params = updatedParams || existingState.retrievalParams;

      // Check if topK or threshold was modified by the student in the UI slider
      const paramsChanged =
        params.topK !== existingState.retrievalParams.topK ||
        params.similarityThreshold !== existingState.retrievalParams.similarityThreshold;

      if (paramsChanged && action === 're_retrieve') {
        console.log('🔄 [API /resume] Parameters modified. Re-running retrieval with new topK/threshold...');
        const state = await runRagWorkflow({
          documentId,
          retrievalParams: params,
          stepStatus: 'IDLE', // Supervisor will route back to retrievalAgent
        });
        res.json({
          success: true,
          message: 'Re-retrieved chunks with updated student parameters.',
          state,
        });
        return;
      }

      // Proceed to generationAgent
      console.log('🚀 [API /resume] Proceeding to Gemini 2.5 Flash Generation...');
      const state = await runRagWorkflow({
        documentId,
        retrievalParams: params,
        stepStatus: 'GENERATING', // Supervisor will route to generationAgent
      });
      res.json({
        success: true,
        message: 'Answer generated by Gemini 2.5 Flash.',
        state,
      });
      return;
    }

    res.json({
      success: true,
      message: 'State unchanged or already completed.',
      state: existingState,
    });
  } catch (error: any) {
    console.error('❌ [API /resume] Error:', error);
    res.status(500).json({ error: error.message || 'Failed to resume RAG workflow.' });
  }
});

export default router;
